[project]
name = "open_dev_python"
version = "0.1.0"
description = "Open Python environment for experiments"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
  | __pycache__
  | notebooks
)/
'''
